-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 16:03:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticketV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketV` DEFAULT CHARACTER SET utf8 ;
USE `ticketV` ;

-- -----------------------------------------------------
-- Table `ticketV`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`projet` (
  `id_projet` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `actif` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`id_projet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`statut` (
  `id_statut` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `actif` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`id_statut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`degre_importance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`degre_importance` (
  `id_degre_importance` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `actif` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`id_degre_importance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`ticket` (
  `id_ticket` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `id_projet` INT ZEROFILL UNSIGNED NOT NULL,
  `id_statut` INT UNSIGNED ZEROFILL NOT NULL,
  `id_degre_importance` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_ticket_projet_idx` (`id_projet` ASC),
  INDEX `fk_ticket_statut1_idx` (`id_statut` ASC),
  INDEX `fk_ticket_degre_importance1_idx` (`id_degre_importance` ASC),
  CONSTRAINT `fk_ticket_projet`
    FOREIGN KEY (`id_projet`)
    REFERENCES `ticketV`.`projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_statut1`
    FOREIGN KEY (`id_statut`)
    REFERENCES `ticketV`.`statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_degre_importance1`
    FOREIGN KEY (`id_degre_importance`)
    REFERENCES `ticketV`.`degre_importance` (`id_degre_importance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`fos_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`fos_user` (
  `id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`projet_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`projet_utilisateur` (
  `id_projet` INT ZEROFILL UNSIGNED NOT NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_projet`, `id_utilisateur`),
  INDEX `fk_projet_has_utilisateur_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_projet_has_utilisateur_projet1_idx` (`id_projet` ASC),
  CONSTRAINT `fk_projet_has_utilisateur_projet1`
    FOREIGN KEY (`id_projet`)
    REFERENCES `ticketV`.`projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_has_utilisateur_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `ticketV`.`fos_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`suivi_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`suivi_ticket` (
  `id_suivi_ticket` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_ticket` INT ZEROFILL UNSIGNED NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `id_statut` INT UNSIGNED ZEROFILL NOT NULL,
  `date` DATETIME NOT NULL,
  `remarque` VARCHAR(255) NULL,
  INDEX `fk_suivi_ticket_ticket1_idx` (`id_ticket` ASC),
  INDEX `fk_suivi_ticket_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_suivi_ticket_statut1_idx` (`id_statut` ASC),
  PRIMARY KEY (`id_suivi_ticket`),
  CONSTRAINT `fk_suivi_ticket_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `ticketV`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suivi_ticket_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `ticketV`.`fos_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suivi_ticket_statut1`
    FOREIGN KEY (`id_statut`)
    REFERENCES `ticketV`.`statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`commentaire_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`commentaire_ticket` (
  `id_commentaire_ticket` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_id_ticket` INT ZEROFILL UNSIGNED NOT NULL,
  `type` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `remarque` VARCHAR(255) NULL,
  PRIMARY KEY (`id_commentaire_ticket`),
  INDEX `fk_commentaire_ticket_ticket1_idx` (`ticket_id_ticket` ASC),
  INDEX `fk_commentaire_ticket_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_commentaire_ticket_ticket1`
    FOREIGN KEY (`ticket_id_ticket`)
    REFERENCES `ticketV`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_ticket_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `ticketV`.`fos_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`tags` (
  `id_tag` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `actif` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`ticket_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`ticket_tags` (
  `ticket_id_ticket` INT ZEROFILL UNSIGNED NOT NULL,
  `tags_id_tag` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`ticket_id_ticket`, `tags_id_tag`),
  INDEX `fk_ticket_has_tags_tags1_idx` (`tags_id_tag` ASC),
  INDEX `fk_ticket_has_tags_ticket1_idx` (`ticket_id_ticket` ASC),
  CONSTRAINT `fk_ticket_has_tags_ticket1`
    FOREIGN KEY (`ticket_id_ticket`)
    REFERENCES `ticketV`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_has_tags_tags1`
    FOREIGN KEY (`tags_id_tag`)
    REFERENCES `ticketV`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketV`.`plage_travail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketV`.`plage_travail` (
  `id_plage` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_ticket` INT ZEROFILL UNSIGNED NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `date_debut` DATETIME NULL,
  `date_fin` DATETIME NULL,
  INDEX `fk_plage_travail_ticket1_idx` (`id_ticket` ASC),
  INDEX `fk_plage_travail_utilisateur1_idx` (`id_utilisateur` ASC),
  PRIMARY KEY (`id_plage`),
  CONSTRAINT `fk_plage_travail_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `ticketV`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plage_travail_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `ticketV`.`fos_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
