<?php

namespace AppBundle\Repository;

/**
 * MiseAjourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseAjourRepository extends \Doctrine\ORM\EntityRepository
{
}
