<?php

namespace AppBundle\Repository;

/**
 * PlageTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageTravailRepository extends \Doctrine\ORM\EntityRepository
{
}
